import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from './api.js';
import homeHtml from '../../../src/pages/page-home.html?raw';
import productsHtml from '../../../src/pages/page-products.html?raw';
import blogHtml from '../../../src/pages/page-blog.html?raw';
import supportHtml from '../../../src/pages/page-support.html?raw';

const emptyProject={name:'',description:'',category:'',technologies:[],demoUrl:'',githubUrl:'',isPublished:false,displayOrder:0};
const emptyService={name:'',description:'',category:'maintenance',icon:'fa-code',features:[],displayOrder:0};
function Toast({message}) { return message && <div className="toast show"><i className="fas fa-check-circle text-green-400"/><span>{message}</span></div>; }
function Shell({page,setPage,children}) { return <><nav className="fixed top-0 z-50 w-full border-b border-slate-800 bg-darker/95 backdrop-blur"><div className="max-w-7xl mx-auto px-4 h-20 flex items-center justify-between"><button onClick={()=>setPage('home')} className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-secondary text-white font-bold text-xl grid place-items-center">Φ</span><b className="gradient-text text-xl">Phi Platform</b></button><div className="hidden md:flex gap-6 text-slate-300">{[['home','الرئيسية'],['products','المنتجات'],['services','الخدمات'],['projects','الأعمال'],['blog','المدونة'],['support','الدعم']].map(([id,label])=><button key={id} onClick={()=>setPage(id)} className={page===id?'text-primary':'hover:text-white'}>{label}</button>)}</div><button onClick={()=>setPage('admin')} className="px-5 py-2 rounded-xl bg-gradient-to-r from-primary to-secondary text-white font-semibold">لوحة الإدارة</button></div></nav>{children}<footer className="border-t border-slate-800 mt-24 py-10 text-center text-slate-500">© 2026 Phi Platform. جميع الحقوق محفوظة.</footer></> }
function PublicHome({setPage}) { return <section className="pt-36"><div className="max-w-7xl mx-auto px-4 text-center py-24"><span className="badge bg-primary/20 text-primary">نحوّل الأفكار إلى واقع رقمي</span><h1 className="text-5xl lg:text-7xl font-black my-7 leading-tight">حلول برمجية <span className="gradient-text">تصنع الفارق</span></h1><p className="text-slate-400 text-lg max-w-2xl mx-auto">نبني منصات ومواقع وتطبيقات موثوقة تساعد أعمالك على النمو.</p><div className="mt-10 flex justify-center gap-4"><button onClick={()=>setPage('request')} className="px-8 py-4 rounded-xl bg-gradient-to-r from-primary to-secondary text-white font-bold liquid-btn">ابدأ مشروعك</button><button onClick={()=>setPage('projects')} className="px-8 py-4 rounded-xl border border-slate-700 text-slate-300">استكشف أعمالنا</button></div></div></section> }
function LegacyPage({html}) {
  const rootRef = useRef(null);

  useEffect(() => {
    const elements = [...rootRef.current.querySelectorAll('.reveal')];
    const reveal = (element) => {
      element.style.opacity = '1';
      element.style.transform = 'translateY(0)';
      element.style.transition = 'opacity 0.8s ease-out, transform 0.8s ease-out';
    };
    if (!('IntersectionObserver' in window)) {
      elements.forEach(reveal);
      return undefined;
    }
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        reveal(entry.target);
        observer.unobserve(entry.target);
      });
    }, { threshold: 0.01, rootMargin: '0px 0px -15% 0px' });
    elements.forEach((element) => observer.observe(element));
    return () => observer.disconnect();
  }, [html]);

  return <div ref={rootRef} dangerouslySetInnerHTML={{__html:html}}/>;
}
function Services({services,setPage}) { const groups=useMemo(()=>[...new Set(services.map(s=>s.category))], [services]); const [group,setGroup]=useState(groups[0]||'maintenance'); useEffect(()=>{if(groups.length&&!groups.includes(group))setGroup(groups[0]);},[groups,group]); return <section className="pt-32 max-w-7xl mx-auto px-4"><header className="text-center mb-12"><h1 className="text-4xl font-bold mb-3">خدماتنا التقنية</h1><p className="text-slate-400">حلول مصممة لاحتياجات مشروعك</p></header><div className="flex flex-wrap gap-3 justify-center mb-10">{groups.map(g=><button key={g} onClick={()=>setGroup(g)} className={'tab-btn '+(group===g?'active':'')}>{g}</button>)}</div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{services.filter(s=>s.category===group).map(s=><article key={s.id} className="glass-card p-7 rounded-2xl"><i className={`fas ${s.icon||'fa-code'} text-3xl text-primary mb-5`}/><h2 className="text-xl font-bold mb-3">{s.name}</h2><p className="text-slate-400 mb-5">{s.description}</p><ul className="space-y-2 text-sm text-slate-300">{s.features.map(f=><li key={f}><i className="fas fa-check text-primary ml-2"/>{f}</li>)}</ul><button onClick={()=>setPage('request')} className="mt-7 text-primary font-semibold">اطلب الخدمة ←</button></article>)}</div></section> }
function Projects({projects}) { return <section className="pt-32 max-w-7xl mx-auto px-4"><header className="text-center mb-12"><h1 className="text-4xl font-bold mb-3">أعمالنا السابقة</h1><p className="text-slate-400">نماذج من مشاريعنا التي نفخر بها</p></header><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{projects.map(p=><article key={p.id} className="glass-card rounded-2xl overflow-hidden group"><div className="h-56 bg-gradient-to-br from-primary/30 to-secondary/30 flex items-center justify-center overflow-hidden">{p.images[0]?<img src={p.images[0].url} className="h-full w-full object-cover" alt={p.name}/>:<i className="fas fa-laptop-code text-7xl text-white/20"/>}</div><div className="p-6"><span className="badge bg-primary/20 text-primary">{p.category}</span><h2 className="text-xl font-bold mt-3">{p.name}</h2><p className="text-slate-400 text-sm mt-2">{p.description}</p><div className="flex flex-wrap gap-2 mt-4">{p.technologies.map(t=><span key={t} className="text-xs text-slate-400">{t}</span>)}</div>{p.demo_url&&<a href={p.demo_url} target="_blank" rel="noreferrer" className="inline-block mt-5 text-primary">عرض المشروع <i className="fas fa-external-link-alt mr-1"/></a>}</div></article>)}</div></section> }
function RequestForm({services,notify}) { const [busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);try{const fd=new FormData(e.currentTarget);await api.post('/requests',fd);e.currentTarget.reset();notify('تم استلام طلبك بنجاح! سنتواصل معك خلال 24 ساعة.');}catch(error){notify(error.message)}finally{setBusy(false)}} return <section className="pt-32 max-w-4xl mx-auto px-4"><header className="text-center mb-10"><h1 className="text-4xl font-bold">اطلب مشروعك المخصص</h1></header><form onSubmit={submit} className="glass rounded-2xl p-8 lg:p-12 space-y-6"><div className="grid md:grid-cols-2 gap-6"><Field label="الاسم الكامل *" name="name" required/><Field label="البريد الإلكتروني *" name="email" type="email" required/></div><div className="grid md:grid-cols-2 gap-6"><Field label="رقم الجوال" name="phone"/><label>الخدمة *<select name="service" required className="form-input w-full rounded-xl py-3 px-4 mt-2"><option value="">اختر الخدمة</option>{services.map(s=><option value={s.name} key={s.id}>{s.name}</option>)}</select></label></div><Field label="الميزانية المتوقعة" name="budget"/><label>وصف المشروع *<textarea name="message" required rows="6" className="form-input w-full rounded-xl py-3 px-4 mt-2"/></label><label className="block">المرفقات (PDF, DOC, PNG, JPG، الحد الأقصى 10MB لكل ملف)<input name="attachments" type="file" multiple accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" className="form-input w-full rounded-xl py-3 px-4 mt-2"/></label><button disabled={busy} className="w-full py-4 rounded-xl bg-gradient-to-r from-primary to-secondary text-white font-bold">{busy?'جارٍ الإرسال...':'إرسال الطلب'}</button></form></section> }
function Field({label,...props}) { return <label className="block">{label}<input {...props} className="form-input w-full rounded-xl py-3 px-4 mt-2"/></label> }
function Login({onLogin,notify}) { const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{await api.post('/auth/login',Object.fromEntries(new FormData(e.currentTarget)));onLogin();}catch(x){notify(x.message)}finally{setBusy(false)}}return <section className="pt-36 max-w-md mx-auto px-4"><form onSubmit={submit} className="glass rounded-2xl p-8 space-y-5"><h1 className="text-2xl font-bold">تسجيل دخول الإدارة</h1><Field label="البريد الإلكتروني" name="email" type="email" required/><Field label="كلمة المرور" name="password" type="password" required/><button disabled={busy} className="w-full py-3 rounded-xl bg-gradient-to-r from-primary to-secondary text-white font-bold">دخول</button></form></section> }
function Admin({notify,onLogout}) { const [tab,setTab]=useState('projects'),[projects,setProjects]=useState([]),[services,setServices]=useState([]),[requests,setRequests]=useState([]),[editing,setEditing]=useState(null); const load=async()=>{try{const [p,s,r]=await Promise.all([api.get('/admin/projects'),api.get('/admin/services'),api.get('/admin/requests')]);setProjects(p.projects);setServices(s.services);setRequests(r.requests)}catch(e){notify(e.message)}};useEffect(()=>{load()},[]);const remove=async(path)=>{if(!confirm('هل تريد الحذف نهائيًا؟'))return;try{await api.delete(path);await load();notify('تم الحذف بنجاح');}catch(e){notify(e.message)}};return <section className="pt-28 max-w-7xl mx-auto px-4"><div className="flex flex-col lg:flex-row gap-8"><aside className="lg:w-64"><div className="glass rounded-2xl p-4 sticky top-24"><div className="p-4 border-b border-slate-700 mb-3"><b>إدارة Phi Platform</b><p className="text-xs text-slate-500 mt-1">حساب المدير</p></div>{[['projects','المشاريع','fa-briefcase'],['services','الخدمات','fa-layer-group'],['requests','طلبات العملاء','fa-inbox'],['settings','إعدادات الحساب','fa-cog']].map(([id,title,icon])=><button key={id} onClick={()=>setTab(id)} className={'sidebar-item w-full flex items-center gap-3 p-3 '+(tab===id?'active':'')}><i className={'fas '+icon}/>{title}{id==='requests'&&<span className="mr-auto badge bg-primary/20 text-primary">{requests.length}</span>}</button>)}<button onClick={onLogout} className="w-full text-right p-3 text-red-400 mt-2">تسجيل الخروج</button></div></aside><main className="flex-1">{tab==='projects'&&<ManageProjects projects={projects} edit={setEditing} remove={remove}/>} {tab==='services'&&<ManageServices services={services} edit={setEditing} remove={remove}/>} {tab==='requests'&&<ManageRequests requests={requests} remove={remove} reload={load}/>} {tab==='settings'&&<PasswordForm notify={notify}/>}</main></div>{editing?.kind==='project'&&<ProjectEditor value={editing.value} close={()=>setEditing(null)} done={async()=>{setEditing(null);await load();notify('تم حفظ المشروع');}}/>}{editing?.kind==='service'&&<ServiceEditor value={editing.value} close={()=>setEditing(null)} done={async()=>{setEditing(null);await load();notify('تم حفظ الخدمة');}}/>}</section> }
function ManageProjects({projects,edit,remove}) { return <div className="glass rounded-2xl p-6"><div className="flex justify-between items-center mb-6"><h1 className="text-2xl font-bold">المشاريع</h1><button onClick={()=>edit({kind:'project',value:emptyProject})} className="px-4 py-2 rounded-xl bg-primary text-white">إضافة مشروع</button></div><div className="space-y-3">{projects.map(p=><div key={p.id} className="p-4 rounded-xl bg-surface/50 border border-slate-700 flex items-center gap-4"><span className={'status-dot '+(p.is_published?'status-completed':'status-active')}/><div className="flex-1"><b>{p.name}</b><p className="text-xs text-slate-500">{p.category} · {p.is_published?'منشور':'مخفي'}</p></div><button onClick={()=>edit({kind:'project',value:{...p,demoUrl:p.demo_url||'',githubUrl:p.github_url||'',isPublished:p.is_published,technologies:p.technologies||[]}})} className="text-primary">تعديل</button><button onClick={()=>remove('/admin/projects/'+p.id)} className="text-red-400">حذف</button></div>)}</div></div> }
function ManageServices({services,edit,remove}) {return <div className="glass rounded-2xl p-6"><div className="flex justify-between items-center mb-6"><h1 className="text-2xl font-bold">الخدمات</h1><button onClick={()=>edit({kind:'service',value:emptyService})} className="px-4 py-2 rounded-xl bg-primary text-white">إضافة خدمة</button></div><div className="space-y-3">{services.map(s=><div key={s.id} className="p-4 rounded-xl bg-surface/50 border border-slate-700 flex items-center gap-4"><i className={'fas '+(s.icon||'fa-code')+' text-primary'}/><div className="flex-1"><b>{s.name}</b><p className="text-xs text-slate-500">{s.category}</p></div><button onClick={()=>edit({kind:'service',value:s})} className="text-primary">تعديل</button><button onClick={()=>remove('/admin/services/'+s.id)} className="text-red-400">حذف</button></div>)}</div></div>}
function ManageRequests({requests,remove,reload}) {return <div className="glass rounded-2xl p-6"><h1 className="text-2xl font-bold mb-6">طلبات العملاء</h1><div className="space-y-4">{requests.map(r=><div key={r.id} className="p-5 rounded-xl bg-surface/50 border border-slate-700"><div className="flex justify-between gap-4"><div><b>{r.name}</b><p className="text-sm text-slate-400">{r.email} {r.phone&&' · '+r.phone}</p></div><button onClick={()=>remove('/admin/requests/'+r.id)} className="text-red-400">حذف</button></div><p className="mt-3">{r.service}</p><p className="text-slate-400 text-sm mt-1">{r.message}</p><div className="flex gap-3 items-center mt-4"><select value={r.status} onChange={async e=>{await api.patch('/admin/requests/'+r.id+'/status',{status:e.target.value});reload();}} className="form-input rounded-lg p-2"><option value="new">جديد</option><option value="in_progress">قيد المعالجة</option><option value="completed">مكتمل</option><option value="archived">مؤرشف</option></select>{r.attachments.map(a=><a key={a.id} href={a.url} target="_blank" className="text-primary text-sm">{a.originalName}</a>)}</div></div>)}</div></div>}
function Modal({title,children,close}){return <div className="fixed inset-0 z-[70] bg-black/70 overflow-auto p-4"><div className="glass max-w-2xl mx-auto my-10 rounded-2xl p-7"><div className="flex justify-between mb-6"><h2 className="text-xl font-bold">{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function ProjectEditor({value,close,done}) {const [v,setV]=useState(value),[files,setFiles]=useState([]),[busy,setBusy]=useState(false);const change=e=>setV({...v,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});async function submit(e){e.preventDefault();setBusy(true);try{const fd=new FormData();for(const [k,x] of Object.entries(v))fd.append(k,k==='technologies'?JSON.stringify(x):x);files.forEach(f=>fd.append('images',f));await (v.id?api.put('/admin/projects/'+v.id,fd):api.post('/admin/projects',fd));done()}finally{setBusy(false)}}return <Modal title={v.id?'تعديل مشروع':'إضافة مشروع'} close={close}><form onSubmit={submit} className="space-y-4"><Field label="اسم المشروع" name="name" value={v.name} onChange={change} required/><label>الوصف<textarea name="description" value={v.description} onChange={change} required className="form-input w-full rounded-xl p-3 mt-2"/></label><div className="grid md:grid-cols-2 gap-4"><Field label="التصنيف" name="category" value={v.category} onChange={change} required/><Field label="التقنيات (مفصولة بفواصل)" value={v.technologies.join(', ')} onChange={e=>setV({...v,technologies:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></div><div className="grid md:grid-cols-2 gap-4"><Field label="رابط Demo" name="demoUrl" type="url" value={v.demoUrl} onChange={change}/><Field label="رابط GitHub" name="githubUrl" type="url" value={v.githubUrl} onChange={change}/></div><label>صور المشروع<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles([...e.target.files])} className="form-input w-full rounded-xl p-3 mt-2"/></label><label className="flex gap-2"><input type="checkbox" name="isPublished" checked={v.isPublished} onChange={change}/> منشور في الموقع العام</label><button disabled={busy} className="w-full py-3 rounded-xl bg-primary text-white">حفظ</button></form></Modal>}
function ServiceEditor({value,close,done}) {const [v,setV]=useState(value),[busy,setBusy]=useState(false);const change=e=>setV({...v,[e.target.name]:e.target.value});async function submit(e){e.preventDefault();setBusy(true);try{await(v.id?api.put('/admin/services/'+v.id,v):api.post('/admin/services',v));done()}finally{setBusy(false)}}return <Modal title={v.id?'تعديل خدمة':'إضافة خدمة'} close={close}><form onSubmit={submit} className="space-y-4"><Field label="اسم الخدمة" name="name" value={v.name} onChange={change} required/><label>الوصف<textarea name="description" value={v.description} onChange={change} required className="form-input w-full rounded-xl p-3 mt-2"/></label><div className="grid md:grid-cols-2 gap-4"><Field label="القسم" name="category" value={v.category} onChange={change} required/><Field label="Font Awesome Icon" name="icon" value={v.icon||''} onChange={change}/></div><Field label="الميزات (مفصولة بفواصل)" value={(v.features||[]).join(', ')} onChange={e=>setV({...v,features:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/><button disabled={busy} className="w-full py-3 rounded-xl bg-primary text-white">حفظ</button></form></Modal>}
function PasswordForm({notify}) {const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(d.newPassword!==d.confirmPassword)return notify('كلمتا المرور غير متطابقتين');setBusy(true);try{await api.put('/auth/password',{currentPassword:d.currentPassword,newPassword:d.newPassword});e.currentTarget.reset();notify('تم تغيير كلمة المرور');}catch(x){notify(x.message)}finally{setBusy(false)}}return <div className="glass rounded-2xl p-6 max-w-xl"><h1 className="text-2xl font-bold mb-6">تغيير كلمة المرور</h1><form onSubmit={submit} className="space-y-4"><Field label="كلمة المرور الحالية" name="currentPassword" type="password" required/><Field label="كلمة المرور الجديدة (12 حرفًا على الأقل)" name="newPassword" type="password" required/><Field label="تأكيد كلمة المرور" name="confirmPassword" type="password" required/><button disabled={busy} className="px-6 py-3 rounded-xl bg-primary text-white">حفظ كلمة المرور</button></form></div>}
export default function App(){const [page,setPage]=useState('home'),[services,setServices]=useState([]),[projects,setProjects]=useState([]),[admin,setAdmin]=useState(null),[toast,setToast]=useState('');const notify=m=>{setToast(m);setTimeout(()=>setToast(''),3500)};useEffect(()=>{window.navigateTo=(x)=>setPage(x==='portfolio'?'projects':x==='dashboard'?'admin':x);window.showToast=notify;window.toggleMobileMenu=()=>document.getElementById('mobileMenu')?.classList.toggle('open');window.filterProducts=(category,btn)=>{document.querySelectorAll('.filter-chip').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');document.querySelectorAll('.product-item').forEach(x=>x.style.display=category==='all'||x.dataset.category===category?'block':'none')};window.searchProducts=q=>document.querySelectorAll('.product-item').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q.toLowerCase())?'block':'none');window.submitProjectRequest=e=>e.preventDefault();window.submitTicket=e=>{e.preventDefault();notify('تم إرسال التذكرة بنجاح')};return()=>['navigateTo','showToast','toggleMobileMenu','filterProducts','searchProducts','submitProjectRequest','submitTicket'].forEach(k=>delete window[k])},[]);useEffect(()=>{Promise.all([api.get('/services'),api.get('/projects')]).then(([s,p])=>{setServices(s.services);setProjects(p.projects)}).catch(e=>notify(e.message));api.get('/auth/me').then(x=>setAdmin(x.user)).catch(()=>{});},[]);let content=page==='home'?<LegacyPage html={homeHtml}/>:page==='products'?<LegacyPage html={productsHtml}/>:page==='blog'?<LegacyPage html={blogHtml}/>:page==='support'?<LegacyPage html={supportHtml}/>:page==='services'?<Services services={services} setPage={setPage}/>:page==='projects'?<Projects projects={projects}/>:page==='request'?<RequestForm services={services} notify={notify}/>:admin?<Admin notify={notify} onLogout={async()=>{await api.post('/auth/logout');setAdmin(null);setPage('home')}}/>:<Login notify={notify} onLogin={async()=>{const x=await api.get('/auth/me');setAdmin(x.user)}}/>;return <><Shell page={page} setPage={setPage}>{content}</Shell><Toast message={toast}/></>}
